version: "3"

services:
  webserver:
    image: davidecesarano/docker-compose-lamp
    restart: always
    ports: 
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      # - target: 80
      #   published: 80
      #   protocol: tcp
      #   mode: host
      # - target: 443
      #   published: 443
      #   protocol: tcp
      #   mode: host
    links: 
      - mysql
    volumes:
      - ./www:/var/www/html
      - ./config/apache2/custom.conf:/etc/apache2/mods-enabled/my.conf
      - ./config/php/php.ini:/etc/php/7.2/apache2/conf.d/custom.ini 
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./ssl:/etc/letsencrypt

  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
